name: Semantic release
on: push
jobs:
  sem-rel:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: go-semantic-release/action@v1
      with:
        GH_TOKEN: ${{ secrets.PAT }}
        github-token: ${{ secrets.PAT }}